apiVersion: v1
kind: Service
metadata:
  name: devops-project
spec:
  type: ClusterIP
  selector:
    app: devops-project
  ports:
    - port: 80        # Service port
      targetPort: 8080  # Container port
