name: DevOpsProject CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # Example: linters still run in parallel
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install ruff black
      - run: ruff check .
      - run: black --check .

  # --- Build Job ---
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devops-project:${{ github.sha }} .

      - name: Save image for later jobs
        run: docker save devops-project:${{ github.sha }} -o image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  # --- Test Job ---
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Run container
        run: docker run -d -p 8080:8080 --name devops-test devops-project:${{ github.sha }}

      - name: Run healthcheck test
        run: curl --retry 5 --retry-connrefused http://localhost:8080/healthz

      - name: Run pytest inside container
        run: docker exec devops-test pytest -q

  # --- Deploy Job ---
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker tag devops-project:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-project:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            deploy/kubernetes/deployment.yaml
            deploy/kubernetes/service.yaml
          images: |
            ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          namespace: default
